### ISSUE TITLE
Make these routes --HIGH PRIORITY

### ISSUE THREAD

**Issue by pershanti** [pershanti/snapcatch#6]
Route to login
Route to main page
Logout 
Show full deck 
*******submit a catch

**Comment by NSMobileCS** [comment]
Route to login: ----------------> / [views.index] (if user credentials valid, redirect below, else login page)
Route to main page: ------------> /snapcatch  
Logout:   /logout --------------> /logout
Show full deck __________
*******submit a catch ___}------> /caught
